class Hypermarket{
	public static void main(String[] LuLu){
		String fruits[] = {"Cavendish Banana","Robusta Banana","Yelakki Banana","Washington Apple","Fuji Apple","Shimla Apple","Alphonso Mango","Badami Mango","Pomegranate","Papaya","Pineapple","Watermelon","Muskmelon","Green Grapes","Black Grapes","Kiwi","Dragon Fruit","Thai Guava","Pears","Oranges","Valencia Oranges","Mosambi","Strawberries","Blueberries","Custard Apple"};
		String veggies[] = {"Potato","Red Onion","Hybrid Tomato","Desi Tomato","Cauliflower","Cabbage","Lady Finger","French Beans","Carrot","Beetroot","Capsicum","Bell Peppers","Brocolli","Zucchini","Bottle Gourd","Ridge Gourd","Bitter Gourd","Ginger","Garlic","Greeen Chillies","Lemon","Spinach","Coriander Leaves","Mint Leaves","Curry Leaves"};
		String toys[] = {"Hot Wheels","LEGO","Barbie","Beyblade","Nerf Blasters","Monopoly","Scrabble","UNO","Rubik's Cube","Fisher-Price Rattle","RC Cars","Soft Plushies","Kitchen Play Sets","Doctor Play Kits","Jigsaw Puzzles","Play-Doh Clay","Cricket Bat","Football","Badminton Rackets","Skating Shoes","Tricycles","Action Figures","Transformers","Musical Keyboards","Chess"};
		String sweets[] = {"Kaju Katli","Motichoor Laddoo","Gulab Jamun","Rasgulla","Mysore Pak","Milk Peda","Dharwad Peda","Soan Papdi","Halwa","Badam Halwa","Rasmalai","Jalebi","Besan Laddoo","Coconut Barfi","Malai Sandwich","Cham Cham","Balushahi","Kala Jamun","Anjeer Barfi","Ghevar","Sandesh","Kalakand","Boondi","Shrikand"};
		String dairy[] = {"Amul Milk","Nandini Milk","Paneer","Salted Butter","Unsalted Butter","Mozzarella Chesse","Chesse Slices","Chesse Spread","Greek Yogurt","Set Curd","Buttermilk","Lassi","Fresh Cream","Condensed Milk","Milk Powder","Ghee","White Eggs","Brown Eggs","Organic Eggs","Flavoured Milk","Tofu","Margarine","Whipped Cream","Yakult Drink","Sour Cream"};
		String electronics[] = {"Apple Iphone","Samsung Galaxy S Series","OnePlus SmartPhones","HP Laptops","Dell Laptops","Apple Macbook","Sony Bravia TV","Samsung QLED TV","LG OLED TV","Bluetooth Speakers","BoAt Earphones","Sony ANC Headphones","Apple Airpods","Power Banks","Smartwatches","Hard Drives","Pendrives","DSLR Camera","Gaming Consoles","Mouse","Keyboard","Tablets","Soundbards","CCTV Cameras","Smart Home Plugs"};
		String kitchenAppliances[] = {"Gas Stove","Induction Cooktop","Mixer Grinder","Juicer Mixer","OTG","Microwave Oven","Refrigerator","Washing Machine","Water Purifier","Coffee Maker","Electric Kettle","Pressure Cooker","Non-Stick Tawa","Kadai","Air Fryer","Hand Blender","Sandwich Maker","Pop-up Toaster","Rice Cooker","Dishwasher","Food Processor","Wet Drinder","Chopper","Chimney","Vaccum Sealer"};
		String beverages[] = {"Coke","Pepsi","Thumbs Up","Sprite","7-Up","Mirinda","Maaza","Frooti","Real Fruit Juice","Tropicana","Red Bull","Monster","Paper Boat","Mineral Water","Sparkling Water","Tonic Water","Ginger Ale","Coconut Water","Cold Coffee","Iced Tea","Tang","Gatorade","Jeera Soda","Appy Fizz","Soda Water"};
		String bakery[] = {"White Bread","Brown Bread","Multigrain Bread","Garlic Bread","Burger Buns","Pizza Base","Fruit Cake","Plum Cake","Chocolate Pastry","Red Velvet Cake","Pineapple Cake","Blackforest Cake","Butter Croissants","Chocolate Donuts","Apple Pie","Muffins","Cupcakes","Puffs","Samosas","Cookies","Rusks","Breadsticks","Brownies","Tarts","Bagels"};
		String grains[] = {"Basmati Rice","Sona Masuri RIce","Ponni Rice","Brown Rice","Wheat Flour","Maida","Besan","Ragi Flour","Bajra Flour","Suji","Toor Dal","Moong Dal","Masoor Dal","Chana Dal","Urad Dal","Rajma","Kabuli Chana","Black Chana","Green Peas","Soya Chunks","Poha","Sabudana","Daliya","Vermicelli","Oats"};
		String snacks[] = {"Lay's","Kurkure","Bingo Mad Angles","Pringles","Bhujia","Moong Dal","Parle-G","GOod Day","Oreo","Dark Fantasy","Hide & Seek","Marie Gold","Monaco Crackers","Bourbon","Digestives","Roasted Makhana","Nachos","Popcorn","Chakli","Banana Chips","Mixture","Peanuts","Cashwes","Almonds","Trail Mix"};
		String personalCare[] = {"Dove Soap","Dettol Soap","Pears Soap","Shampoo","Conditioner","Hair Mask","Body Lotion","Vaseline Jelly","Toothpaste","Toothbrush","Mouthwash","Shaving Cream","Shaving Razors","Deodrant","Body Spray","Perfume","Face Wash","Moisturizer","Talcum Powder","Sanitary Pads","Diapers","Hand Sanitizer","Cotton Buds","Face Tissues","Wet Wipes"};
		String householdCleaning[] = {"Detergent Powder","Liquid Detergent","Rin Bar","Dishwash Gel","Pril Liquid","Scrubber","Toilet Cleaner","Floor Cleaner","Glass Cleaner","Dettol Spray","Air Freshener","Godrej Spray","Mop and Bucket Set","Broom","Dustpan","Garbage Bags","Aluminium Foil","Cling Film","Kitchen Towels","Toilet Paper Rolls","Napthalene Balls","Bleach","Drain CLeaner","SHoe Polish"};
		String frozenFoods[] = {"Green Peas","Sweet Corn","Mixed Veggies","French Fries","Potato Wedges","Burger Patties","Chicken Nuggets","Chicken Sausages","Parathas","Idli/Dosa Batter","Momos","Paneer Tikka","Fish FIllets","Prawns","Ice Cream","Pizza","Kebabs","Samosas","Berries","Waffles","Smileys","Cheese Corn Nuggets","Malai Kofta","Rasgullas"};
		String chocolates[] = {"Cadbury Diary Milk","Ferrero Rocher","Snickers","Mars Bar","Kit Kat","Perk","Munch","5 Star","Lindt Excellence","Toblerone","Bournville","Kinder Joy","Gems","Milkybar","Lollipops","Mentos Mints","Center Fresh Gum","Pulse Candy","Fox's Crystal Clear","Skittles","M&M's","Hersheys's Kisses","Nutella","Chocolate Syrup","Marshmallows"};
		String spices[] = {"Turmeric Powder","Red Chilli Powder","Coriander Powder","Garam Masala","Chicken Masala","Biryani Masala","Sambar Powder","Rasam Powder","Rasam Powder","Cumin Seeds","Mustard Seeds","Black Pepper","Cardamom","Cinnamon Sticks","Cloves","Bay Leaves","Kasturi Methi","Hing","Ketchup","Mayonnaise","Siracha Sauce","Soy Sauce","Vinegar","Green Chilli Sauce","Pasta Sauce","Pizza Topping"};
		String teaAndCoffee[] = {"Tata Tea Gold","Red Label Tea","Taj Mahal Tea","Society","Wagh Bakri Tea","Green Tea","Chamomile Tea","Earl Grey Tea","Nescafe Classic Instant Coffee","Bru Gold","Davidoff Coffee","Starbucks Roast Beans","Filter Coffee Powder","Continental Xtra","Sleepy Owl Cold Brew","Levista Coffee","Masala Tea Bags","Lemon Tea","Honey","Jaggery Powder","Sugar","Brown Sugar","Stevia","Coffee Creamer","Hot Chocolate Powder"};
		String babyCare[] = {"Johnson's Baby Shampoo","Himalayan Baby Lotion","Baby Wash","Baby Diapers","Baby Wipes","Cerelac","Baby Formula","Baby Oil","Diaper Rash Cream","Baby Powder","Feeding Bottles","Pacifiers","Teethers","Baby Nail Clippers","Sipper Cups","Baby Bedding Sets","Bibs","Baby Strollers","Car Seats","Baby Walkers","Soft Blankets","High Chairs","Baby Bathtubs","Baby Laundry Detergent","Potty Training Seats"};
		String fashion[] = {"Cotton T-Shirts","Formals Shirts","Blue Jeans","Cargo Pants","Kurti","Leggings","Saree","Handbags","Frocks","Pajamas","Socks","Ties","Belts","Formal Leather Shoes","Sports Shoes","Flip-Flops","Raincoats","Sweaters","Tracksuits","Swimwear","Sunglasses","Wallets","Backpacks","Caps/Hats","Handkerchiefs","Thermal Innerwear"};
		String luggage[] = {"Hard-Shell Suitcase","Soft-Shell Suitcase","Cabin Bags","Duffel Bags","Gym Bags","Laptop Bags","Travel Neck Pillows","Eye Masks","Luggage Locks","Luggage Tags","Toiletry Bottles","Travel Adapters","Passport Holders","Rain Covers","Foldable Travel Bags","Money Belts","Compreession Cubes","Hiking Backpacks","Trolley Bags","Camera Bags","Messenger Bags","Waist Pouches","Buisness Briefcases","Garment Bags"};
		
		System.out.println("The Fruits available in the Hypermarket are:");
		for(String fruit:fruits) System.out.println(fruit);
		System.out.println("The Veggies available in the Hypermarket are:");
		for(String vegetable:veggies) System.out.println(vegetable);
		System.out.println("The toys available in the Hypermarket are:");
		for(String toysAvail:toys) System.out.println(toysAvail);
		System.out.println("The Sweets available in the Hypermarket are:");
		for(String sweet:sweets) System.out.println(sweet);
		System.out.println("The dairy products available in the Hypermarket are:");
		for(String dairyProdcuts:dairy) System.out.println(dairyProdcuts);
		System.out.println("The electronics available in the Hypermarket are:");
		for(String gadgets:electronics) System.out.println(gadgets);
		System.out.println("The kitchenAppliances available in the Hypermarket are:");
		for(String appliances:kitchenAppliances) System.out.println(appliances);
		System.out.println("The beverages available in the Hypermarket are:");
		for(String drinks:beverages) System.out.println(drinks);
		System.out.println("The bakery items available in the Hypermarket are:");
		for(String cafe:bakery) System.out.println(cafe);
		System.out.println("The grain types available in the Hypermarket are:");
		for(String grain:grains) System.out.println(grain);
		System.out.println("The snacks available in the Hypermarket are:");
		for(String namkeen:snacks) System.out.println(namkeen);
		System.out.println("The personal care products available in the Hypermarket are:");
		for(String care:personalCare) System.out.println(care);
		System.out.println("The household cealning products available in the Hypermarket are:");
		for(String house:householdCleaning) System.out.println(house);
		System.out.println("The frozen foods available in the Hypermarket are:");
		for(String frozen:frozenFoods) System.out.println(frozen);
		System.out.println("The chocolates available in the Hypermarket are:");
		for(String choco:chocolates) System.out.println(choco);
		System.out.println("The spices available in the Hypermarket are:");
		for(String spice:spices) System.out.println(spice);
		System.out.println("The tea and coffee products available in the Hypermarket are:");
		for(String coffee:teaAndCoffee) System.out.println(coffee);
		System.out.println("The baby care products available in the Hypermarket are:");
		for(String baby:babyCare) System.out.println(baby);
		System.out.println("The fashion items available in the Hypermarket are:");
		for(String fashionItems:fashion) System.out.println(fashionItems);
		System.out.println("The luggage types available in the Hypermarket are:");
		for(String bag:luggage) System.out.println(bag);
	}
}
